# Generated by Django 3.0.6 on 2020-07-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxitem',
            name='expiration',
            field=models.DateField(),
        ),
    ]
