# Generated by Django 3.0.6 on 2020-07-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxitem',
            name='image',
            field=models.ImageField(upload_to='boxitem'),
        ),
    ]
