# Generated by Django 3.0.6 on 2020-07-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[('Vegan', 'vegan'), ('Vegetarian', 'vegetarian'), ('Mixed', 'mixed'), ('Test', 'Test')], default='Mixed', max_length=12),
        ),
    ]
