# Generated by Django 3.0.6 on 2020-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('sugar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxitem',
            name='reserve',
            field=models.ManyToManyField(blank=True, related_name='reserving', to='users.Profile'),
        ),
    ]
