# Generated by Django 3.0.6 on 2020-07-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugar_app', '0002_auto_20200716_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
