# Generated by Django 3.0.6 on 2020-07-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugar_app', '0003_auto_20200716_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxitem',
            name='expiration',
            field=models.DateTimeField(),
        ),
    ]
