# Generated by Django 3.0.8 on 2020-07-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugar_app', '0002_boxitem_reserve'),
        ('sugar_app', '0004_auto_20200716_0047'),
    ]

    operations = [
    ]
