# Generated by Django 3.0.8 on 2020-07-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20200713_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='address',
            field=models.ManyToManyField(blank=True, to='locations.Location'),
        ),
    ]
